/*
alert('Hello, world!');
console.log('Hello, world!');*/

//var nome = "Caio";
//alert(nome);
//console.log("Olá",nome,"Tenha um bom dia!");

//let nome ="Caio"
//alert(nome);
//console.log(nome);

//const nome = "Caio Iuri"

//alert(nome);

//const userName = prompt("Digite o seu nome")
//const userName = parseInt(prompt("Digite o seu nome"))
//const comprar = confirm("Digite o seu nome")

/*let num01 = parseInt(prompt("Digite o primeiro numero"));
let num02 = parseInt(prompt("Digite o segundo numero"));

let soma = num01 + num02;

alert(soma);

let num03 = parseInt(prompt("Digite o primeiro numero"));
let num04 = parseInt(prompt("Digite o segundo numero"));

let subtração = num03 - num04;

alert(subtração);

let num05 = parseInt(prompt("Digite o primeiro numero"));
let num06 = parseInt(prompt("Digite o segundo numero"));

let divisão = num05 / num06;

alert(divisão);

let num07 = parseInt(prompt("Digite o primeiro numero"));
let num08 = parseInt(prompt("Digite o segundo numero"));

let multiplicação = num07 * num08;

alert(multiplicação); */

/*let first_name = "Caio";
let alterado = first_name.concat("" + "Iuri");

console.log(alterado);*/

/*let nome = prompt("Digite o seu nome");
let idade = parseInt(prompt("Digite sua idade"));
let dados = `Meu nome é ${nome} e eu tenho ${idade} anos.`;

console.log (dados);*/

let a = 10
let b = 5

console.log(`A:${a} B${b}`)

a = a + b
b = a - b
